# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 193.0.168.222/32
    cni.projectcalico.org/podIPs: 193.0.168.222/32
    kubernetes.io/psp: vmware-system-privileged
  creationTimestamp: "2022-04-28T07:46:51Z"
  labels:
    role: spring-app
    spring-app-id: test04-0qooondnxl
    spring-deployment-id: test04-0qooondnxl
    task-name: test04
  name: test04-0qooondnxl
  namespace: springcloud-test01
  resourceVersion: "66238229"
  uid: af8fee0d-2fa8-4bc9-8e4b-9d14470a27a2
spec:
  containers:
    - args:
        - --management.metrics.tags.service=task-application
        - --spring.datasource.username=dataflow
        - --spring.datasource.url=jdbc:mariadb://springcloud01-mariadb:3306/dataflow?useMysqlMetadata=true
        - --spring.datasource.driverClassName=org.mariadb.jdbc.Driver
        - --management.metrics.tags.application=${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}
        - --spring.cloud.task.name=test04
        - --spring.datasource.password=change-me
        - --spring.cloud.task.executionid=11
      env:
        - name: SPRING_CLOUD_APPLICATION_GUID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
      image: milkliver/springcloudtask01
      imagePullPolicy: IfNotPresent
      command: ["tail", "-f", "/dev/null"]
      name: test04-lqnnnk9kve
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-cq7kd
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: docker-secret
  nodeName: cns-tkc01p-workers-47ngn-657d98b6cd-29rfw
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: default-token-cq7kd
      secret:
        defaultMode: 420
        secretName: default-token-cq7kd
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-04-28T07:46:51Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-04-28T07:46:51Z"
      message: "containers with unready status: [test04-lqnnnk9kve]"
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-04-28T07:46:51Z"
      message: "containers with unready status: [test04-lqnnnk9kve]"
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-04-28T07:46:51Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://9ba7840fe4dbc07b4e91ce44e94995a59fb64ab86982fafdc6a2a5ebd82971dd
      image: docker.io/milkliver/springcloudtask01:latest
      imageID: docker.io/milkliver/springcloudtask01@sha256:07192142e26b1a6f33e69ccdbf36a5b58a55b8e3d5a64eba2c61eea1cc80735c
      lastState: {}
      name: test04-lqnnnk9kve
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: containerd://9ba7840fe4dbc07b4e91ce44e94995a59fb64ab86982fafdc6a2a5ebd82971dd
          exitCode: 128
          finishedAt: "2022-04-28T07:46:52Z"
          message:
            'failed to create containerd task: OCI runtime create failed: container_linux.go:380:
            starting container process caused: exec: "--management.metrics.tags.service=task-application":
            executable file not found in $PATH: unknown'
          reason: StartError
          startedAt: "1970-01-01T00:00:00Z"
  hostIP: 10.250.120.60
  phase: Failed
  podIP: 193.0.168.222
  podIPs:
    - ip: 193.0.168.222
  qosClass: Guaranteed
  startTime: "2022-04-28T07:46:51Z"
