apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-springboot
  labels:
    name: deploy-test
    app: springboot

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: deploy-test

  template:
    metadata:
      labels:
        app: deploy-test
    spec:
      #      serviceAccountName: AA
      #      securityContext:
      #        runAsUser: 0
      #        runAsGroup: 0
      #        fsGroup: 0
      #        allowPrivilegeEscalation: true
      #        privileged: true
      imagePullSecrets:
        - name: harbor-secret

      containers:
        - name: deploy-test-springboot
          image: 192.168.50.11/seyana/deploy-test
          workingDir: /testfiles
          command: ["/bin/java", "-jar", "deploy-test.jar"]
          #command: ["tail","-f","/dev/null"]
          ports:
            - name: deploy-test
              containerPort: 9527
              protocol: TCP
