{{- if eq .Values.environment "uat" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-test.fullname" . }}-uat
data:
  application.properties: |
  {{- range $key, $value := .Values.serverProperties }}
    {{ $key }}={{ $value }}
    environment=uat
    server.address=0.0.0.0
    server.port=9527
    spring.thymeleaf.cache=false
    spring.thymeleaf.enabled=true
    spring.thymeleaf.prefix=classpath:/templates/
    spring.thymeleaf.suffix=.html
    spring.jmx.enabled=true
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.metrics.enabled=true
    management.endpoint.env.enabled=true
  {{- end }}
{{- end }}