{{- if eq .Values.environment "prd" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-test.fullname" . }}-prd
data:
  application.properties: |
    version=@project.version@
    environment=PRD
    server.address=0.0.0.0
    server.port=9527
    spring.thymeleaf.cache=false
    spring.thymeleaf.enabled=true
    spring.thymeleaf.prefix=classpath:/templates/
    spring.thymeleaf.suffix=.html
    spring.jmx.enabled=true
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.metrics.enabled=true
    management.endpoint.env.enabled=true

{{- end }}