{{- if and .Values.ingress.enabled (or .Values.ingress.selfHostsEnabled .Values.ingress.customHostsEnabled) -}}
{{- $fullName := include "deploy-test.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "deploy-test.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.selfHostsEnabled }}
    - host: {{ .Values.ingress.hostname | default (printf "%s.%s.%s" (.Values.subdomain | default "argocd-ingress" ) .Release.Namespace (include "deploy-test.fullname" .)) }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }}
         
    {{- if .Values.ingress.customHostsEnabled }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .backend.serviceName }}
              servicePort: {{ .backend.servicePort }}
              #serviceName: {{ $fullName }}
              #servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
