{{- if and (.Values.imagePullSecrets) }}
{{- if and (.Values.imagePullSecrets.harborsecret) }}
{{- if and (.Values.imagePullSecrets.harborsecret.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: harborsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "harborImagePullSecret" . }}
{{- end }}
{{- end }}
{{- end }}